### PR TITLE
OWFace: Changed to replace current paths with new instead of adding new column

### PR DESCRIPTION
**Pull request by PrimozGodec**
https://github.com/biolab/lookalike-demo/issues/6

Before face widget added a new column with face images. It is now changed such that previous paths are replaced with new.

### CODE REVIEW

**Comment by markotoplak** [comment]
Why is a problem with Neighbors being solved this way?

**Comment by PrimozGodec** [comment]
@markotoplak another option would be fixing Neighbours such that when checking the domain compatibility it does not consider meta attributes. I was told that Neighbours should stay as they are.

**Comment by ajdapretnar** [comment]
@markotoplak This was done at the suggestion of @janezd. Perhaps he can explain why this is better.

**Comment by PrimozGodec** [comment]
Closing this pull via https://github.com/biolab/orange3/pull/3555

**Pull request closed without merging**
